### ISSUE TITLE
Password generator breaks bitcore.

### ISSUE THREAD

**Issue by daniel-farina** [BTCPrivate/bitcore-install#12]
The password generator for the installer breaks Bitcore. The password should only be alphanumeric. 

[The code on this line](https://github.com/BTCPrivate/bitcore-install/blob/89986e0b0bd84a49b88ccf0eb42b1f247f654b06/btcp_store_demo.sh#L87)

so this:
```
head -c 32 /dev/urandom | base64
```
will generate random strings which sometimes include + symbols as shown on the image below:
![image](https://user-images.githubusercontent.com/13665117/42556295-1efccd62-84b9-11e8-9c7f-6bdcd2ecff68.png)

**Comment by interbiznw** [comment]
Wasn't this solved and pulled in from upstream @daniel-farina ?

**Comment by daniel-farina** [comment]
Yes, this was corrected by merging several repos.
